### ISSUE TITLE
Cronograma e Entregas

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T03-PortalGalt#4]
- pq as sprints 4 e 7, que são mais curtas?

Revejam.

**Comment by BrunoOLiveirax** [comment]
Ajuste nas datas das sprints para alinhar melhor com o progresso do desenvolvimento.
 Reorganização das atividades a serem feitas em cada sprint com base em prioridades novas.
 Atualização do planejamento de funcionalidades para cada etapa do projeto.
 Definição de novas metas de entrega para alinhar com o cronograma ajustado.
 Revisão das dependências entre tarefas e ajustes nas entregas para cada sprint.
